openapi: 3.1.0
info:
  title: Abc Corp
  description: ''
  version: 1.0.0
tags:
  - name: Interactions
paths:
  /api/v4/locations/loc_id/reviews:
    get:
      summary: interactions
      deprecated: false
      description: >-
        This endpoint retrieves all interactions (e.g., reviews, comments) for a
        specific location identified by its encoded ID. It includes details
        about each review, such as its content, author information, rating, and
        responses provided by the business.
      tags:
        - Interactions
      parameters:
        - name: loc_id
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          description: ''
          required: true
          example: '{{api_key}}'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      interactions:
                        type: object
                        properties:
                          pageInfo:
                            type: object
                            properties:
                              hasNextPage:
                                type: boolean
                              hasPreviousPage:
                                type: boolean
                              endCursor:
                                type: 'null'
                              total:
                                type: 'null'
                            required:
                              - hasNextPage
                              - hasPreviousPage
                              - endCursor
                              - total
                          edges:
                            type: array
                            items:
                              type: object
                              properties:
                                node:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    interactionId:
                                      type: string
                                    source:
                                      type: string
                                    title:
                                      type: 'null'
                                    content:
                                      type: string
                                    locationDbId:
                                      type: 'null'
                                    locationEncodedId:
                                      type: string
                                    authorName:
                                      type: string
                                    authorAvatar:
                                      type: string
                                    authorUrl:
                                      type: string
                                    authorInfo:
                                      type: 'null'
                                    rating:
                                      type: integer
                                    date:
                                      type: string
                                    permalink:
                                      type: string
                                    category:
                                      type: string
                                    type:
                                      type: string
                                    photoUrl:
                                      type: 'null'
                                    photoThumbnailUrl:
                                      type: 'null'
                                    responded:
                                      type: boolean
                                    notes:
                                      type: 'null'
                                    responses:
                                      type: array
                                      items:
                                        type: object
                                        properties:
                                          interactionId:
                                            type: string
                                          source:
                                            type: string
                                          title:
                                            type: 'null'
                                          content:
                                            type: string
                                          locationDbId:
                                            type: 'null'
                                          locationEncodedId:
                                            type: 'null'
                                          authorName:
                                            type: string
                                          authorAvatar:
                                            type:
                                              - string
                                              - 'null'
                                          authorUrl:
                                            type:
                                              - string
                                              - 'null'
                                          authorInfo:
                                            type: 'null'
                                          rating:
                                            type: 'null'
                                          date:
                                            type: string
                                          permalink:
                                            type: 'null'
                                          category:
                                            type: string
                                          type:
                                            type: string
                                          photoUrl:
                                            type: 'null'
                                          photoThumbnailUrl:
                                            type: 'null'
                                          responded:
                                            type: 'null'
                                          notes:
                                            type: 'null'
                                          responseCount:
                                            type: 'null'
                                          canRespond:
                                            type: 'null'
                                          totalResponses:
                                            type: 'null'
                                          locationId:
                                            type: 'null'
                                          respondedWith:
                                            type: 'null'
                                          respondedBy:
                                            type:
                                              - integer
                                              - 'null'
                                          interactionStatus:
                                            type:
                                              - string
                                              - 'null'
                                        required:
                                          - interactionId
                                          - source
                                          - title
                                          - content
                                          - locationDbId
                                          - locationEncodedId
                                          - authorName
                                          - authorAvatar
                                          - authorUrl
                                          - authorInfo
                                          - rating
                                          - date
                                          - permalink
                                          - category
                                          - type
                                          - photoUrl
                                          - photoThumbnailUrl
                                          - responded
                                          - notes
                                          - responseCount
                                          - canRespond
                                          - totalResponses
                                          - locationId
                                          - respondedWith
                                          - respondedBy
                                          - interactionStatus
                                    responseCount:
                                      type: 'null'
                                    canRespond:
                                      type: boolean
                                    totalResponses:
                                      type: integer
                                    locationId:
                                      type: integer
                                    respondedWith:
                                      type: 'null'
                                    respondedBy:
                                      type: 'null'
                                  required:
                                    - id
                                    - interactionId
                                    - source
                                    - title
                                    - content
                                    - locationDbId
                                    - locationEncodedId
                                    - authorName
                                    - authorAvatar
                                    - authorUrl
                                    - authorInfo
                                    - rating
                                    - date
                                    - permalink
                                    - category
                                    - type
                                    - photoUrl
                                    - photoThumbnailUrl
                                    - responded
                                    - notes
                                    - responses
                                    - responseCount
                                    - canRespond
                                    - totalResponses
                                    - locationId
                                    - respondedWith
                                    - respondedBy
                                cursor:
                                  type: string
                              required:
                                - node
                                - cursor
                          totalCount:
                            type: integer
                        required:
                          - pageInfo
                          - edges
                          - totalCount
                    required:
                      - interactions
                required:
                  - data
              examples:
                '1':
                  summary: Success
                  value:
                    data:
                      interactions:
                        pageInfo:
                          hasNextPage: false
                          hasPreviousPage: false
                          endCursor: null
                          total: null
                        edges:
                          - node:
                              id: bbfebdaa-3ae5-4205-ae0d-c15c7071abf3
                              interactionId: bbfebdaa-3ae5-4205-ae0d-c15c7071abf3
                              source: facebook.com
                              title: null
                              content: >-
                                i would have signed up a contract with them for
                                school books if they had all the haryana state
                                board books, but they don't sadly.
                              locationDbId: null
                              locationEncodedId: TG9jYXRpb246Nzc5OTE=
                              authorName: KBS High School
                              authorAvatar: >-
                                http://graph.facebook.com/6611144952298569/picture
                              authorUrl: https://www.facebook.com/111012697295849/reviews
                              authorInfo: null
                              rating: 1
                              date: '2023-06-08T10:31:42+00:00'
                              permalink: https://www.facebook.com/111012697295849
                              category: Recommendation
                              type: Review
                              photoUrl: null
                              photoThumbnailUrl: null
                              responded: true
                              notes: null
                              responses:
                                - interactionId: 5663dba8-2219-477e-ac96-c803c354c906
                                  source: facebook.com
                                  title: null
                                  content: >-
                                    Dear KBS High School, thank you for
                                    considering Rice - Carter for your school
                                    book needs. We appreciate your feedback
                                    regarding the Haryana state board books
                                    availability. We are constantly updating our
                                    inventory to better serve our customers and
                                    will take your request into consideration.
                                    If there's anything else we can assist you
                                    with, please feel free to reach out. Thank
                                    you for sharing your thoughts with us.
                                  locationDbId: null
                                  locationEncodedId: null
                                  authorName: Owner
                                  authorAvatar: null
                                  authorUrl: null
                                  authorInfo: null
                                  rating: null
                                  date: '2024-05-24T06:29:47.069477+00:00'
                                  permalink: null
                                  category: Review
                                  type: Comment
                                  photoUrl: null
                                  photoThumbnailUrl: null
                                  responded: null
                                  notes: null
                                  responseCount: null
                                  canRespond: null
                                  totalResponses: null
                                  locationId: null
                                  respondedWith: null
                                  respondedBy: 1327
                                  interactionStatus: COMPLETED
                              responseCount: null
                              canRespond: true
                              totalResponses: 1
                              locationId: 77991
                              respondedWith: null
                              respondedBy: null
                            cursor: >-
                              SW50ZXJhY3Rpb246MV8xNjg2MjIwMzAyMDAwLWJiZmViZGFhLTNhZTUtNDIwNS1hZTBkLWMxNWM3MDcxYWJmMw==
                        totalCount: 1
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers: []
