openapi: 3.1.0
info:
  title: Abc Corp
  description: ''
  version: 1.0.0
tags:
  - name: Listings API
paths:
  /locations/TG9jYXRpb246NzAzNTY1/listings/premium:
    get:
      summary: Retrieve Premium Listings for a Location
      deprecated: false
      description: |
        This endpoint retrieves premium listings for a specified location.

        The location is identified by a unique ID included in the URL path.

        - **Authorization Required**: This endpoint requires an API key.
        - **Location ID**: Use a valid location ID in the path.
        - **API Key**: Pass API key as Bearer token in `Authorization` header.
      tags:
        - Listings API
      parameters:
        - name: Authorization
          in: header
          description: |
            Your API key for authentication. Use the format:
            ```
            Authorization: Bearer 
            ```
          required: true
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: |
            A successful response containing the premium listings for the
            specified location.
          content:
            application/json:
              schema:
                type: object
                properties:
                  listings:
                    type: array
                    description: A list of premium listings.
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier for the listing.
                        title:
                          type: string
                          description: The title of the premium listing.
                        url:
                          type: string
                          description: The URL of the listing.
              examples:
                '1':
                  summary: Success Example
                  value:
                    listings:
                      - id: '12345'
                        title: Premium Listing Example
                        url: https://example.com/listing/12345
          headers: {}
        '401':
          description: Unauthorized. The request requires a valid API key.
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        '404':
          description: Location not found.
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers: []
