openapi: 3.0.0
info:
  title: Synup API
  description: |
    Welcome to Synup's API. You can use this API to access endpoints such as Locations, Listings, Analytics, and more.
  version: 1.0.0

servers:
  - url: https://api.example.com/
    description: Main API Server

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: |
        To authorize, use the API key provided for your account. 
        Example: `API {your_api_key}`

  schemas:
    SubCategory:
      type: object
      properties:
        id:
          type: string
          example: "1234"
        name:
          type: string
          example: "Restaurants"

security:
  - ApiKeyAuth: []
