openapi: 3.0.1
info:
  title: Abc Corp
  description: ''
  version: 1.0.0
tags:
  - name: Listings API
paths:
  /locations/TG9jYXRpb246NzAzNTY1/listings/premium:
    get:
      summary: Retrieve Premium Listings for a Location
      deprecated: false
      description: >
        This endpoint retrieves premium listings for a specified location.

        The location is identified by a unique ID included in the URL path.


        - **Authorization Required**: This endpoint requires an API key. 

        - **Location ID**: Use a valid location ID in the path.

        - **API Key**: Pass your API key as a Bearer token in the
        `Authorization` header.
      tags:
        - Listings API
        - L1
      parameters:
        - name: Authorization
          in: header
          description: |
            Your API key for authentication. Use the format:
            ```
            Authorization: Bearer {{api_key}}
            ```
          required: true
          example: '{{api_key}}'
          schema:
            type: string
      responses:
        '200':
          description: >
            A successful response containing the premium listings for the
            specified location.
          content:
            application/json:
              schema:
                type: object
                properties:
                  listings:
                    type: array
                    description: A list of premium listings.
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier for the listing.
                        title:
                          type: string
                          description: The title of the premium listing.
                        url:
                          type: string
                          description: The URL of the listing.
              examples:
                '1':
                  summary: Success Example
                  value:
                    listings:
                      - id: '12345'
                        title: Premium Listing Example
                        url: https://example.com/listing/12345
          headers: {}
        '401':
          description: Unauthorized. The request requires a valid API key.
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        '404':
          description: Location not found.
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /locations/TG9jYXRpb246NzM0NTE=/listings/duplicates:
    get:
      summary: Get duplicate listings for location
      deprecated: false
      description: ''
      tags:
        - Listings API
        - Listings Copy
      parameters:
        - name: page
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          description: ''
          required: false
          example: '{{api_key}}'
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /locations/listings/duplicates:
    get:
      summary: Duplicate Listings Rollup
      deprecated: false
      description: ''
      tags:
        - Listings API
        - Listings
      parameters:
        - name: Authorization
          in: header
          description: ''
          required: true
          example: your_api_key_here
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /locations/listings/mark-as-duplicate:
    post:
      summary: Mark as duplicate
      deprecated: false
      description: ''
      tags:
        - Listings API
        - Listings
      parameters:
        - name: Authorization
          in: header
          description: ''
          required: true
          example: your_api_key_here
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: object
                  properties:
                    locationId:
                      type: string
                    listingItemIds:
                      type: array
                      items:
                        type: string
                  required:
                    - locationId
                    - listingItemIds
              required:
                - input
            example:
              input:
                locationId: TG9jYXRpb246NzM1Mzc=
                listingItemIds:
                  - TGlzdGluZ0l0ZW06MzMzMjkyOQ==
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /locations/listings/mark-as-not-duplicate:
    post:
      summary: Mark as not duplicate
      deprecated: false
      description: ''
      tags:
        - Listings API
        - Listings
      parameters:
        - name: Authorization
          in: header
          description: ''
          required: true
          example: your_api_key_here
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: object
                  properties:
                    listingItemIds:
                      type: array
                      items:
                        type: string
                    locationId:
                      type: string
                  required:
                    - listingItemIds
                    - locationId
              required:
                - input
            example:
              input:
                listingItemIds:
                  - TGlzdGluZ0l0ZW06MzMzMjkzOA==
                locationId: test1
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /api/v1/users:
    get:
      summary: Test Get users
      deprecated: false
      description: Retrieves a list of users
      tags:
        - Listings API
      parameters:
        - name: limit
          in: query
          description: Specifies the maximum number of records to return per page.
          required: false
          example: '10'
          schema:
            type: string
        - name: page
          in: query
          description: Indicates the current page of the results you want to retrieve.
          required: false
          example: '1'
          schema:
            type: string
      responses:
        '200':
          description: Indicated that the required number of pages are fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID
                required:
                  - id
              examples:
                '1':
                  summary: Success
                  value: |-
                    [
                        {
                            "id": 1,
                            "name": "John Doe"
                        },
                        {
                            "id": 2,
                            "name": "Jane Doe"
                        }
                    ]'
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []

components:
  schemas: {}
  securitySchemes: {}
servers: []
