---
openapi: 3.0.1
info:
  title: Abc Corp
  description: ""
  version: 1.0.0
tags:
  - name: Platform
paths:
  /api/v4/locations/{locationId}/listings/duplicates:
    get:
      summary: Fetch duplicate locations (Test)
      deprecated: false
      description: Retrieves duplicate listings for a location
      tags:
        - Platform
      parameters:
        - name: locationId
          in: path
          description: >-
            Location_id's are base64 encoded (eg: TG9jYXRpb246MTIzNDU2) and have
            to be decoded (eg: Location:123456) to reveal the entity id's
          required: true
          example: TG9jYXRpb246MTA2MDY4MQ==
          schema:
            type: string
        - name: page
          in: query
          description: ''
          required: false
          example: ''
          schema:
            type: string
        - name: Authorization
          in: header
          description: ''
          required: true
          example: API rnYm2SBgqH8dTOizP9BeT0IntSI
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      duplicateListingsForLocation:
                        type: array
                        items:
                          type: object
                          properties:
                            primaryListingUrl:
                              type: 'null'
                            siteId:
                              type: string
                            siteName:
                              type: string
                            siteUrl:
                              type: string
                            duplicateListings:
                              type: array
                              items:
                                type: object
                                properties:
                                  addressValid:
                                    type: boolean
                                  city:
                                    type: string
                                  street:
                                    type: string
                                  state:
                                    type: 'null'
                                  postalCode:
                                    type: string
                                  phone:
                                    type: string
                                  phoneValid:
                                    type: boolean
                                  name:
                                    type: string
                                  nameValid:
                                    type: boolean
                                  duplicateProcessingState:
                                    type: string
                                  liveLink:
                                    type: string
                                  id:
                                    type: string
                                  countryCode:
                                    type: string
                                required:
                                  - addressValid
                                  - city
                                  - street
                                  - state
                                  - postalCode
                                  - phone
                                  - phoneValid
                                  - name
                                  - nameValid
                                  - duplicateProcessingState
                                  - liveLink
                                  - id
                                  - countryCode
                    required:
                      - duplicateListingsForLocation
                  locationID:
                    type: string
                required:
                  - data
                  - locationID
              examples:
                '1':
                  summary: Success
                  value:
                    data:
                      duplicateListingsForLocation:
                        - primaryListingUrl: null
                          siteId: U2l0ZTo0OA==
                          siteName: Hotfrog
                          siteUrl: hotfrog.com
                          duplicateListings:
                            - addressValid: false
                              city: Basel
                              street: Steinengraben 69
                              state: null
                              postalCode: '4051'
                              phone: |
                                --- 061 2725353
                                ...
                              phoneValid: true
                              name: Hotel Steinenschanze
                              nameValid: false
                              duplicateProcessingState: POTENTIAL
                              liveLink: https://www.hotfrog.ch/company/1122808198332416
                              id: TGlzdGluZ0l0ZW06NzQ4Mjg3Njk=
                              countryCode: ch
                            - addressValid: false
                              city: Basel
                              street: Steinengraben 69
                              state: null
                              postalCode: '4051'
                              phone: |
                                --- 061 272 53 53
                                ...
                              phoneValid: true
                              name: Steinenschanze Stadthotel Basel
                              nameValid: false
                              duplicateProcessingState: POTENTIAL
                              liveLink: https://www.hotfrog.ch/company/1122794778542080
                              id: TGlzdGluZ0l0ZW06NzQ4Mjg3Njg=
                              countryCode: ch
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        '401':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers: []
