openapi: 3.0.0
info:
  title: New Collection
  version: 1.0.0
servers:
  - url: http://{{v4_end_point}}
tags:
  - name: Listings Copy
paths:
  /locations/TG9jYXRpb246NzAzNTY1/listings/premium:
    get:
      tags:
        - Listings Copy
      summary: Get Premium listings for a location
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: '{{api_key}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
