name: Create Project on Apidog

# This allows you to manually trigger the workflow and pass a custom client name
on:
  workflow_dispatch:
    inputs:
      client_name:
        description: 'Client Name'
        required: true
        default: 'Test Client'
      logo_url:
        description: 'Client Logo URL'
        required: true
        default: 'https://example.com/logo.png'
      base_url:
        description: 'Client Base URL'
        required: true
        default: 'https://app.apidog.com'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to use it in the job
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install the dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      # Run the Playwright test with the provided client name
      - name: Run Playwright test
        run: |
          pytest -s tests/test_createproject.py --client_name "${{ github.event.inputs.client_name }}" --client_logo_url "${{ github.event.inputs.client_logo_url }}" --client_base_url "${{ github.event.inputs.client_base_url }}"

        # Upload the project_ids.txt file as an artifact for inspection
      - name: Upload project_ids.txt artifact
        uses: actions/upload-artifact@v3
        with:
          name: project_ids
          path: project_ids.txt

      # Optional: Commit changes if the project_ids.txt was modified
      - name: Commit changes to project_ids.txt
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add project_ids.txt
          git commit -m "Update project_ids.txt with new project ID" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
