name: Export Individual Apidog APIs to GitHub

on:
  workflow_dispatch:
    inputs:
      api_ids:
        description: 'Comma-separated list of API endpoint IDs to export individually'
        required: true
        default: ''

jobs:
  export_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Set up API IDs
        id: set_api_ids
        run: |
          API_IDS="${{ github.event.inputs.api_ids }}"
          echo "API_IDS=$API_IDS" >> $GITHUB_ENV

      - name: Export Each API from Apidog
        id: export_apis
        run: |
          IFS=',' read -ra ID_ARRAY <<< "$API_IDS"

          for ENDPOINT_ID in "${ID_ARRAY[@]}"; do
            # Make the API call to export the endpoint
            RESPONSE=$(curl --location --request POST "https://api.apidog.com/v1/projects/${{ secrets.APIDOG_PROJECT_ID }}/export-openapi" \
              --header "X-Apidog-Api-Version: 2024-03-28" \
              --header "Content-Type: application/json" \
              --header "Authorization: Bearer ${{ secrets.APIDOG_EXPORT_API_KEY }}" \
              --data "{
                \"scope\": {
                  \"type\": \"SELECTED_ENDPOINTS\",
                  \"selectedEndpointIds\": [$ENDPOINT_ID]
                },
                \"options\": {
                  \"includeApidogExtensionProperties\": false,
                  \"addFoldersToTags\": false
                },
                \"oasVersion\": \"3.1\",
                \"exportFormat\": \"YAML\"
              }")

            # Debug: Print the response
            echo "$RESPONSE"

            # Save the response to a temporary file
            TEMP_FILE="temp_export_${ENDPOINT_ID}.yaml"
            echo "$RESPONSE" > "$TEMP_FILE"

            # Extract the method and path for the file name
            METHOD=$(yq e '.[keys[0]].get // .[keys[0]].post // .[keys[0]].put // .[keys[0]].delete' "$TEMP_FILE" | head -n 1)  # Extract the method dynamically
            PATH=$(yq e 'keys[0]' "$TEMP_FILE")  # Extract the first path
            
            # Extract the last two segments of the path
            LAST_TWO=$(echo "$PATH" | awk -F'/' '{print $(NF-1) "_" $NF}')  # Get last two segments
            
            FILE_NAME="${METHOD}_${LAST_TWO}.yaml"  # Construct the file name

            # Move the temporary file to the final named file
            mv "$TEMP_FILE" "$FILE_NAME"
          done

      - name: Commit exported YAML files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Add each exported YAML file to Git
          for FILE in exported_api_*.yaml; do
            git add "$FILE"
          done

          git commit -m "Exported individual APIs from Apidog"
          git push
