name: Export Individual Apidog APIs to GitHub

on:
  workflow_dispatch:
    inputs:
      api_ids:
        description: 'Comma-separated list of API endpoint IDs to export individually'
        required: true
        default: ''

jobs:
  export_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Set up API IDs
        id: set_api_ids
        run: |
          API_IDS="${{ github.event.inputs.api_ids }}"
          echo "API_IDS=$API_IDS" >> $GITHUB_ENV

      - name: Export Each API from Apidog
        id: export_apis
        run: |
          IFS=',' read -ra ID_ARRAY <<< "$API_IDS"

          for ENDPOINT_ID in "${ID_ARRAY[@]}"; do
            # Make the API call to export the endpoint
            RESPONSE=$(curl --location --request POST "https://api.apidog.com/v1/projects/${{ secrets.APIDOG_PROJECT_ID }}/export-openapi" \
              --header "X-Apidog-Api-Version: 2024-03-28" \
              --header "Content-Type: application/json" \
              --header "Authorization: Bearer ${{ secrets.APIDOG_EXPORT_API_KEY }}" \
              --data "{
                \"scope\": {
                  \"type\": \"SELECTED_ENDPOINTS\",
                  \"selectedEndpointIds\": [\"$ENDPOINT_ID\"]
                },
                \"options\": {
                  \"includeApidogExtensionProperties\": false,
                  \"addFoldersToTags\": false
                },
                \"oasVersion\": \"3.1\",
                \"exportFormat\": \"YAML\"
              }")

            if [ -z "$RESPONSE" ]; then
              echo "Failed to fetch API for endpoint ID: $ENDPOINT_ID" >&2
              exit 1
            fi

            # Save the raw response to a temporary file
            TEMP_FILE="temp_export_${ENDPOINT_ID}.yaml"
            echo "$RESPONSE" | yq eval -P > "$TEMP_FILE"

            # Debug: Print the file content
            echo "Exported API YAML content:"
            cat "$TEMP_FILE"

            # Extract the HTTP method and path
            PATH=$(yq e '.paths | keys | .[0]' "$TEMP_FILE")
            METHOD=$(yq e ".paths[\"$PATH\"] | keys | .[0]" "$TEMP_FILE")  # Correct indexing for method

            if [ -z "$METHOD" ] || [ -z "$PATH" ]; then
              echo "Failed to parse method or path for endpoint ID: $ENDPOINT_ID" >&2
              exit 1
            fi

            # Extract the last two segments of the path for the file name
            LAST_TWO=$(echo "$PATH" | awk -F'/' '{print $(NF-1) "_" $NF}')
            FILE_NAME="${METHOD}_${LAST_TWO}.yaml"

            # Rename the temporary file
            mv "$TEMP_FILE" "$FILE_NAME"
          done

      - name: Commit exported YAML files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          for FILE in *.yaml; do
            git add "$FILE"
          done

          git commit -m "Exported individual APIs from Apidog"
          git push
