name: Run Playwright Script

on:
  workflow_dispatch:
    inputs:
      client_name:
        description: 'Client Name to provide to the script'
        required: true
        default: 'Client Name'

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run Playwright test
      run: |
        python -m playwright install
        python script.py "${{ github.event.inputs.client_name }}"

    - name: Commit changes to project_ids.txt
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add project_ids.txt
        git commit -m "Update project_ids.txt with new project ID"
        git push
