name: Run Playwright Test

# This allows you to manually trigger the workflow and pass a custom client name
on:
  workflow_dispatch:
    inputs:
      client_name:
        description: "Client Name to use in the test"
        required: true
        default: "Default Client Name"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to use it in the job
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install the dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      # Run the Playwright test with the provided client name
      - name: Run Playwright test
        run: |
          pytest tests/test_createproject.py --client_name "${{ github.event.inputs.client_name }}"
