name: YAML Lint

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '!.github/workflows/*.yaml'
      - '!.github/workflows/*.yml'
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '!.github/workflows/*.yaml'
      - '!.github/workflows/*.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Check changed YAML files
        id: changed_yaml
        run: |
          CHANGED_YAML_FILES=$(git diff --name-only HEAD~1 HEAD -- '*.yaml' '*.yml' ':!**/.github/workflows/*')
          if [ -z "$CHANGED_YAML_FILES" ]; then
            echo "No relevant YAML files changed."
            exit 0
          fi
          echo "$CHANGED_YAML_FILES" > changed_files.txt

      - name: Run yamllint on changed files
        if: success()
        run: |
          xargs yamllint < changed_files.txt
