name: YAML Import Scheduler

on:
  workflow_run:
    workflows: ["Pages Build and Deployment"]  # The name of your Pages build workflow
    types:
      - completed

jobs:
  yaml_import_scheduler:
    runs-on: ubuntu-latest

    # Check if the Pages Build and Deployment completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch the last 2 commits for comparison

      - name: Check for Changed YAML Files
        id: check_yaml
        run: |
          # Get all YAML files that were added or modified in the previous push
          CHANGED_YAML_FILES=$(git diff --name-only HEAD~1 HEAD | grep ".yaml" || true)

          # If no YAML files were changed, exit
          if [ -z "$CHANGED_YAML_FILES" ]; then
            echo "No YAML files changed. Exiting."
            exit 0
          fi

          # Construct the URLs for all changed YAML files and store them
          YAML_URLS=""
          for FILE in $CHANGED_YAML_FILES; do
            YAML_URL="https://bharath-synup.github.io/apidog-docs/$FILE"
            YAML_URLS+="$YAML_URL "
          done

          # Output YAML URLs
          echo "YAML_URLS=$YAML_URLS"
          echo "::set-output name=YAML_URLS::$YAML_URLS"

      - name: Read Project IDs
        id: read_ids
        run: |
          # Read the project IDs from project_ids.txt and store them in the environment
          while read -r line; do
            echo "PROJECT_ID=$line" >> $GITHUB_ENV
          done < project_ids.txt

      - name: Schedule Import for All Projects
        run: |
          # Read project IDs from the environment and loop through them
          for PROJECT_ID in ${{ env.PROJECT_ID }}; do
            for YAML_URL in ${{ steps.check_yaml.outputs.YAML_URLS }}; do
              echo "Scheduling import for $YAML_URL in project $PROJECT_ID"

              curl --location "https://api.apidog.com/v1/projects/$PROJECT_ID/import-openapi?locale=en-US" \
                --header "X-Apidog-Api-Version: 2024-03-28" \
                --header "Content-Type: application/json" \
                --header "Accept: application/json" \
                --header "Authorization: Bearer ${{ secrets.APIDOG_API_KEY }}" \
                --data "{
                    \"input\": {
                        \"url\": \"$YAML_URL\"
                    }
                }"
            done
          done

      - name: Confirm URLs Scheduled
        run: |
          echo "YAML files have been scheduled for import to all projects with URLs:"
          echo "${{ steps.check_yaml.outputs.YAML_URLS }}"
