name: YAML Import Scheduler

on:
  push:
    paths:
      - '*.yaml'   # Trigger the action when any YAML file is pushed or updated

jobs:
  schedule_import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch more commit history (previous 2 commits)

      - name: Read Project IDs
        id: read_ids
        run: |
          # Read the project IDs from project_ids.txt, storing them into the environment
          while read -r line; do
            echo "PROJECT_ID=$line" >> $GITHUB_ENV
          done < project_ids.txt

      - name: Set YAML file URLs
        id: yaml_urls
        run: |
          # Get all YAML files that were added or modified in this push
          CHANGED_YAML_FILES=$(git diff --name-only --diff-filter=AMR HEAD~1 HEAD | grep ".yaml")

          # Construct the URLs for all changed YAML files and store them
          YAML_URLS=""
          for FILE in $CHANGED_YAML_FILES; do
            YAML_URL="https://bharath-synup.github.io/apidog-docs/$FILE"
            YAML_URLS+="$YAML_URL "
          done

          # Output YAML URLs
          echo "YAML_URLS=$YAML_URLS"
          echo "::set-output name=YAML_URLS::$YAML_URLS"

      - name: Schedule Import for All Projects
        run: |
          # Read project IDs from the environment and loop through them
          for PROJECT_ID in ${{ env.PROJECT_ID }}; do
            for YAML_URL in ${{ steps.yaml_urls.outputs.YAML_URLS }}; do
              echo "Scheduling import for $YAML_URL in project $PROJECT_ID"

              curl --location "https://api.apidog.com/v1/projects/$PROJECT_ID/import-openapi?locale=en-US" \
                --header "X-Apidog-Api-Version: 2024-03-28" \
                --header "Content-Type: application/json" \
                --header "Accept: application/json" \
                --header "Authorization: Bearer ${{ secrets.APIDOG_API_KEY }}" \
                --data "{
                    \"input\": {
                        \"url\": \"$YAML_URL\"
                    }
                }"
            done
          done

      - name: Confirm URLs scheduled
        run: |
          echo "YAML files have been scheduled for import to all projects with URLs:"
          echo "${{ steps.yaml_urls.outputs.YAML_URLS }}"
